site_name: "Magic: The Gathering Ontology"
site_description: >-
  An ontology describing the card game Magic: The Gathering.
site_author: "Cyril Matthey-Doret"
copyright: >-
  The literal information presented on this site about Magic:
  The Gathering, such as Oracle text, is © Wizards of
  the Coast, LLC, a subsidiary of Hasbro, Inc. This site is not
  produced by or endorsed by Wizards of the Coast. All other
  content is released under GPLv3 © 2023 Cyril Matthey-Doret.
theme:
  name: material
  logo: logo.png
  features:
    - content.tabs.link
    - content.code.annotate
#  palette:
#    scheme: slate
#    primary: cyan
plugins:
  - search
  - mermaid2
nav:
#  - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://cmdoret.github.io/mtg_ontology
repo_url: https://github.com/cmdoret/mtg_ontology

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Uncomment this block to enable use of Google Analytics. 
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
